--- #YAML:1.0
name:               Prima
version:            1.34
abstract:           a perl graphic toolkit
author:
    - Dmitry Karasik <dmitry@karasik.eu.org>
license:            BSD
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
resources:
    homepage:    http://www.prima.eu.org/
    repository:  http://github.com/dk/Prima
no_index:
    directory:
        - t
        - inc
        - include
        - img
        - test
        - os2
        - unix
        - win32
    file:
        - Makefile.PL
        - test.pl
        - ms_install.pl
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
