--- #YAML:1.0
name:               Prima
version:            1.31
abstract:           a perl graphic toolkit
author:
    - Dmitry Karasik <dmitry@karasik.eu.org>
license:            BSD
homepage:           http://www.prima.eu.org/
repository:         http://github.com/dk/Prima
distribution_type:  module
no_index:
    directory:
        - include
        - img
        - os2
        - test
        - unix
        - win32
    file:
        - Makefile.PL
        - test.pl
        - ms_install.pl
generated_by:       Prima/Makefile.PL
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
